from app.db.models import AuctionPropertyType

data_origin_url = "https://torgidv.ru/"
urls = {
    AuctionPropertyType.bankruptcy: "https://torgidv.ru/bankrupt/",
    AuctionPropertyType.arrested: "https://torgidv.ru/sales/",
}

bankrupt_form_data = {
    "draw": "1",
    "columns[0][data]": "0",
    "columns[0][searchable]": "true",
    "columns[0][orderable]": "true",
    "columns[0][search][regex]": "false",
    "columns[1][data]": "1",
    "columns[1][searchable]": "true",
    "columns[1][orderable]": "true",
    "columns[1][search][regex]": "false",
    "columns[2][data]": "2",
    "columns[2][searchable]": "true",
    "columns[2][orderable]": "true",
    "columns[2][search][regex]": "false",
    "columns[3][data]": "3",
    "columns[3][searchable]": "true",
    "columns[3][orderable]": "true",
    "columns[3][search][regex]": "false",
    "columns[4][data]": "4",
    "columns[4][searchable]": "true",
    "columns[4][orderable]": "true",
    "columns[4][search][regex]": "false",
    "columns[5][data]": "5",
    "columns[5][searchable]": "true",
    "columns[5][orderable]": "true",
    "columns[5][search][regex]": "false",
    "columns[6][data]": "6",
    "columns[6][searchable]": "true",
    "columns[6][orderable]": "true",
    "columns[6][search][regex]": "false",
    "order[0][column]": "2",
    "order[0][dir]": "desc",
    "start": "0",
    "length": "100",
    "search[regex]": "false",
    "signedParameters": "YTozOntzOjEwOiJDQUNIRV9USU1FIjtpOjYwO3M6MTg6IkNPTVBPTkVOVF9URU1QTEFURSI7czowOiIiO3M6MTA6IlRSQURFX1RZUEUiO3M6OToidHJhZGVfMTI3Ijt9.cd08c8086fd96f41a32cc60f57f592b20d785401a3ecb377eda5ea0706c76eaa",
    "filter[lots][IBLOCK_SECTION_ID]": "38",
    "filter[trades][IBLOCK_SECTION_ID]": "35",
}

sales_form_data = {
    "draw": "2",
    "columns[0][data]": "0",
    "columns[0][name]": "",
    "columns[0][searchable]": "true",
    "columns[0][orderable]": "true",
    "columns[0][search][value]": "",
    "columns[0][search][regex]": "false",
    "columns[1][data]": "1",
    "columns[1][name]": "",
    "columns[1][searchable]": "true",
    "columns[1][orderable]": "true",
    "columns[1][search][value]": "",
    "columns[1][search][regex]": "false",
    "columns[2][data]": "2",
    "columns[2][name]": "",
    "columns[2][searchable]": "true",
    "columns[2][orderable]": "true",
    "columns[2][search][value]": "",
    "columns[2][search][regex]": "false",
    "columns[3][data]": "3",
    "columns[3][name]": "",
    "columns[3][searchable]": "true",
    "columns[3][orderable]": "true",
    "columns[3][search][value]": "",
    "columns[3][search][regex]": "false",
    "columns[4][data]": "4",
    "columns[4][name]": "",
    "columns[4][searchable]": "true",
    "columns[4][orderable]": "true",
    "columns[4][search][value]": "",
    "columns[4][search][regex]": "false",
    "columns[5][data]": "5",
    "columns[5][name]": "",
    "columns[5][searchable]": "true",
    "columns[5][orderable]": "true",
    "columns[5][search][value]": "",
    "columns[5][search][regex]": "false",
    "columns[6][data]": "6",
    "columns[6][name]": "",
    "columns[6][searchable]": "true",
    "columns[6][orderable]": "true",
    "columns[6][search][value]": "",
    "columns[6][search][regex]": "false",
    "order[0][column]": "2",
    "order[0][dir]": "desc",
    "start": "0",
    "length": "100",
    "search[value]": "",
    "search[regex]": "false",
    "signedParameters": "YTozOntzOjEwOiJDQUNIRV9USU1FIjtpOjg2NDAwO3M6MTg6IkNPTVBPTkVOVF9URU1QTEFURSI7czowOiIiO3M6MTA6IlRSQURFX1RZUEUiO3M6OToidHJhZGVfMjI5Ijt9.abbacb90c235eaa94f4b6e9af1b6b68feb8cf782fc1ad557b6ce1adeb68565dd",
    "filter[lots][IBLOCK_SECTION_ID]": "46",
    "filter[trades][IBLOCK_SECTION_ID]": "36",
}
