post_data_pagination = {
    "javax.faces.partial.ajax": "true",
    "javax.faces.source": "formMain:lotListTable",
    "javax.faces.partial.execute": "formMain:lotListTable",
    "javax.faces.partial.render": "formMain:lotListTable",
    "javax.faces.behavior.event": "page",
    "javax.faces.partial.event": "page",
    "formMain:lotListTable_pagination": "true",
    "formMain:lotListTable_first": "0",
    "formMain:lotListTable_rows": "50",
    "formMain:lotListTable_skipChildren": "true",
    "formMain:lotListTable_encodeFeature": "true",
    "formMain": "formMain",
    "formMain:inputServerTime": "00:00:00",
    "formMain:commonSearchCriteriaStr": "",
    "formMain:inputKeyWordId": "",
    "formMain:orgSubId": "",
    "formMain:debtSubId": "",
    "formMain:fromIdPeriod_input": "",
    "formMain:toIdPeriod_input": "",
    "formMain:fromIdAcceptancePeriod_input": "",
    "formMain:toIdAcceptancePeriod_input": "",
    "formMain:j_idt71": "",
    "formMain:j_idt73": "",
    "formMain:sgTablePanel_collapsed": "false",
    "formMain:taTablePanel_collapsed": "true",
    "formMain:stateTablePanel_collapsed": "true",
    "formMain:j_idt99_scrollState": "0,0",
    "formMain:selectTreeDlgPanel_collapsed": "true",
    "formMain:selectRegTreeDlgPanel_collapsed": "true",
    "formMain:objFilterPanel_collapsed": "false",
    "formMain:lotListTable_rppDD": "50",
    "formMain:selectTreeDlgTree_selection": "",
    "formMain:selectTreeDlgTree_scrollState": "0,0",
    "javax.faces.ViewState": "",
}

post_panel_list_dict = {
    "javax.faces.partial.ajax": "true",
    "javax.faces.source": "formMain:clTable",
    "javax.faces.partial.execute": "formMain:clTable",
    "javax.faces.partial.render": "formMain:panelList formMain:showLotsPanel",
    "formMain:clTable": "formMain:clTable",
    "formMain": "formMain",
    "formMain:sgTablePanel_collapsed": "true",
    "formMain:taTablePanel_collapsed": "true",
    "formMain:stateTablePanel_collapsed": "true",
    "formMain:j_idt120_scrollState": "0,0",
    "formMain:selectTreeDlgPanel_collapsed": "true",
    "formMain:selectRegTreeDlgPanel_collapsed": "true",
    "formMain:lotDataGridId_rppDD": "12",
    "formMain:selectTreeDlgTree_scrollState": "0,0",
}

post_property_type_choose_dict = {
    "javax.faces.partial.ajax": "true",
    "javax.faces.partial.execute": "formMain:sgTablePanel",
    "javax.faces.partial.render": "formMain:sgTablePanel",
    "javax.faces.behavior.event": "valueChange",
    "javax.faces.partial.event": "change",
    "formMain": "formMain",
    "formMain:sgTablePanel_collapsed": "false",
    "formMain:taTablePanel_collapsed": "true",
    "formMain:stateTablePanel_collapsed": "true",
    "formMain:j_idt120_scrollState": "0,0",
    "formMain:selectTreeDlgPanel_collapsed": "true",
    "formMain:selectRegTreeDlgPanel_collapsed": "true",
    "formMain:lotListTable_rppDD": "50",
    "formMain:selectTreeDlgTree_scrollState": "0,0",
}

post_date_dict = {
    "javax.faces.partial.ajax": "true",
    "javax.faces.source": "formMain:cbLotFilterFindId",
    "javax.faces.partial.execute": "@all",
    "javax.faces.partial.render": "formMain",
    "formMain:cbLotFilterFindId": "formMain:cbLotFilterFindId",
    "formMain": "formMain",
    "formMain:sgTablePanel_collapsed": "false",
    "formMain:taTablePanel_collapsed": "true",
    "formMain:stateTablePanel_collapsed": "true",
    "formMain:j_idt120_scrollState": "0,0",
    "formMain:selectTreeDlgPanel_collapsed": "true",
    "formMain:selectRegTreeDlgPanel_collapsed": "true",
    "formMain:lotListTable_rppDD": "50",
    "formMain:selectTreeDlgTree_scrollState": "0,0",
}

post_data_to_trade = {
    "javax.faces.partial.ajax": "true",
    "javax.faces.source": "",
    "javax.faces.partial.execute": "@all",
    "formMain": "formMain",
    "formMain:inputServerTime": "",
    "formMain:commonSearchCriteriaStr": "",
    "formMain:inputKeyWordId": "",
    "formMain:orgSubId": "",
    "formMain:debtSubId": "",
    "formMain:fromIdPeriod_input": "",
    "formMain:toIdPeriod_input": "",
    "formMain:fromIdAcceptancePeriod_input": "",
    "formMain:toIdAcceptancePeriod_input": "",
    "formMain:j_idt71": "",
    "formMain:j_idt73": "",
    "formMain:sgTablePanel_collapsed": "true",
    "formMain:taTablePanel_collapsed": "true",
    "formMain:stateTablePanel_collapsed": "true",
    "formMain:j_idt99_scrollState": "0,0",
    "formMain:selectTreeDlgPanel_collapsed": "true",
    "formMain:selectRegTreeDlgPanel_collapsed": "true",
    "formMain:objFilterPanel_collapsed": "false",
    "formMain:lotListTable_rppDD": "50",
    "formMain:selectTreeDlgTree_selection": "",
    "formMain:selectTreeDlgTree_scrollState": "0,0",
    "javax.faces.ViewState": "",
}

post_data_debitor = {
    "formMain": "formMain",
    "formMain:inputServerTime": "",
    "formMain:commonSearchCriteriaStr": "",
    "formMain:auctionDocsPanel_collapsed": "false",
    "javax.faces.ViewState": "",
}

post_data_lot_tab = {
    "formMain": "formMain",
    "formMain:inputServerTime": "",
    "formMain:commonSearchCriteriaStr": "",
    "formMain:j_idt54": "formMain:j_idt54",
}

post_data_unique_lot_page = {
    "javax.faces.partial.ajax": "true",
    "javax.faces.source": "",
    "javax.faces.partial.execute": "@all",
    "formMain": "formMain",
    "formMain:inputServerTime": "",
    "formMain:commonSearchCriteriaStr": "",
    "javax.faces.ViewState": "",
}

post_data_download = {
    "formMain": "formMain",
    "formMain:inputServerTime": "",
    "formMain:commonSearchCriteriaStr": "",
    "formMain:j_idt59_collapsed": "false",
    "formMain:j_idt74_collapsed": "false",
    "formMain:auctionDocsPanel_collapsed": "false",
    "javax.faces.ViewState": "",
}

post_data_period_offer_page = {
    "javax.faces.partial.ajax": "true",
    "javax.faces.source": "formMain:dataRSList",
    "javax.faces.partial.execute": "formMain:dataRSList",
    "javax.faces.partial.render": "formMain:dataRSList",
    "formMain:dataRSList": "formMain:dataRSList",
    "formMain:dataRSList_pagination": "true",
    "formMain:dataRSList_first": "",
    "formMain:dataRSList_rows": "10",
    "formMain:dataRSList_skipChildren": "true",
    "formMain:dataRSList_encodeFeature": "true",
    "formMain": "formMain",
    "formMain:inputServerTime": "",
    "formMain:commonSearchCriteriaStr": "",
    "formMain:j_idt45_collapsed": "false",
    "formMain:dataRSList_rppDD": "10",
    "formMain:dataRSList_selection": "",
    "formMain:j_idt61_collapsed": "false",
    "javax.faces.ViewState": "",
}
property_type_sgtable_id_map = {"bankruptcy": "1", "arrested": "2", "commercial": "0"}
