"""Initial migration

Revision ID: 9b810025e9ca
Revises: 
Create Date: 2025-03-23 21:53:43.220418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9b810025e9ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('model_type', sa.Enum('Auction', 'Lot', 'DebtorMessage', 'LegalCase', name='filemodeltype'), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_type_model_id', 'files', ['model_type', 'model_id'], unique=False)
    op.create_table('legal_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('court_name', sa.String(length=255), nullable=True),
    sa.Column('debtor_category', sa.String(length=255), nullable=True),
    sa.Column('fedresurs_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('oktmo', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oktmo')
    )
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('counterparties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('kpp', sa.String(length=9), nullable=True),
    sa.Column('snils', sa.String(length=11), nullable=True),
    sa.Column('ogrn', sa.String(length=13), nullable=True),
    sa.Column('ogrnip', sa.String(length=15), nullable=True),
    sa.Column('okopf', sa.String(length=5), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('fedresurs_url', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('individual', 'legal_entity', name='counterpartytype'), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inn')
    )
    op.create_table('counterparty_sro',
    sa.Column('counterparty_id', sa.Integer(), nullable=False),
    sa.Column('sro_id', sa.Integer(), nullable=False),
    sa.Column('message_number', sa.String(length=255), nullable=True),
    sa.Column('activity_type', sa.Text(), nullable=True),
    sa.Column('entered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['sro_id'], ['counterparties.id'], ),
    sa.PrimaryKeyConstraint('counterparty_id', 'sro_id')
    )
    op.create_table('debtor_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('content', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('fedresurs_url', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('debtor_id', sa.Integer(), nullable=False),
    sa.Column('legal_case_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['debtor_id'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['legal_case_id'], ['legal_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('trading_floors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('counterparty_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'disabled', 'archived', name='statustype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auctions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ext_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('number', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('auction', 'competition', 'offer', name='auctiontype'), nullable=False),
    sa.Column('form', sa.Enum('open', 'closed', name='formtype'), nullable=False),
    sa.Column('message_number', sa.String(length=255), nullable=True),
    sa.Column('organizer_id', sa.Integer(), nullable=True),
    sa.Column('arbitrator_id', sa.Integer(), nullable=True),
    sa.Column('debtor_id', sa.Integer(), nullable=True),
    sa.Column('trading_floor_id', sa.Integer(), nullable=False),
    sa.Column('legal_case_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['arbitrator_id'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['debtor_id'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['legal_case_id'], ['legal_cases.id'], ),
    sa.ForeignKeyConstraint(['organizer_id'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['trading_floor_id'], ['trading_floors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('parsers_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trading_floor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'disabled', 'archived', name='statustype'), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trading_floor_id'], ['trading_floors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ext_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('property_info', sa.Text(), nullable=True),
    sa.Column('price_start', sa.Float(), nullable=False),
    sa.Column('price_step', sa.Float(), nullable=True),
    sa.Column('auction_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lot_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=7), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lot_periods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_start_at', sa.DateTime(), nullable=False),
    sa.Column('request_end_at', sa.DateTime(), nullable=True),
    sa.Column('trading_start_at', sa.DateTime(), nullable=True),
    sa.Column('trading_end_at', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lot_periods')
    op.drop_table('lot_categories')
    op.drop_table('lots')
    op.drop_table('parsers_status')
    op.drop_table('auctions')
    op.drop_table('trading_floors')
    op.drop_table('debtor_messages')
    op.drop_table('counterparty_sro')
    op.drop_table('counterparties')
    op.drop_table('cities')
    op.drop_table('addresses')
    op.drop_table('regions')
    op.drop_table('legal_cases')
    op.drop_index('ix_model_type_model_id', table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
