"""Lot.price_start can be nullable

Revision ID: 92571a7e004c
Revises: 9b810025e9ca
Create Date: 2025-03-26 11:34:23.873215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '92571a7e004c'
down_revision: Union[str, None] = '9b810025e9ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lots', 'price_start',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lots', 'price_start',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
