post_data = {
    'ctl00$PrivateOffice1$ctl00': 'ctl00$PrivateOffice1$ctl00|ctl00$cphBody$ibMessagesSearch',
    '__EVENTTARGET': '',
    '__EVENTARGUMENT': '',
    '__VIEWSTATE': '',
    '__VIEWSTATEGENERATOR': '',
    '__PREVIOUSPAGE': '',
    'ctl00$PrivateOffice1$tbLogin': '',
    'ctl00$PrivateOffice1$tbPassword': '',
    'ctl00$PrivateOffice1$cbRememberMe': 'on',
    'ctl00$PrivateOffice1$tbEmailForPassword': '',
    'ctl00_PrivateOffice1_RadToolTip1_ClientState': '',
    'ctl00$DebtorSearch1$inputDebtor': 'поиск',
    'ctl00$cphBody$tbMessageNumber': '',
    'ctl00$cphBody$mdsMessageType$tbSelectedText': '',
    'ctl00$cphBody$mdsMessageType$hfSelectedValue': '',
    'ctl00$cphBody$mdsMessageType$hfSelectedType': '',
    'ctl00$cphBody$ddlCourtDecisionType': '',
    'ctl00$cphBody$mdsPublisher$tbSelectedText': '',
    'ctl00$cphBody$mdsPublisher$hfSelectedValue': '',
    'ctl00$cphBody$mdsPublisher$hfSelectedType': '',
    'ctl00$cphBody$ucRegion$ddlBoundList': '',
    'ctl00$cphBody$mdsDebtor$tbSelectedText': '',
    'ctl00$cphBody$mdsDebtor$hfSelectedValue': '',
    'ctl00$cphBody$mdsDebtor$hfSelectedType': '',
    'ctl00$cphBody$cldrBeginDate$tbSelectedDate': '',
    'ctl00$cphBody$cldrBeginDate$tbSelectedDateValue': '',
    'ctl00$cphBody$cldrEndDate$tbSelectedDate': '',
    'ctl00$cphBody$cldrEndDate$tbSelectedDateValue': '',
    '__ASYNCPOST': 'true',
    'ctl00$cphBody$ibMessagesSearch.x': '',
    'ctl00$cphBody$ibMessagesSearch.y': '',
}


post_data_pagination = {
    'ctl00$PrivateOffice1$ctl00': '',
    '__EVENTTARGET': '',
    '__EVENTARGUMENT': '',
    '__VIEWSTATE': '',
    '__VIEWSTATEGENERATOR': '',
    '__PREVIOUSPAGE': '',
    'ctl00$PrivateOffice1$tbLogin': '',
    'ctl00$PrivateOffice1$tbPassword': '',
    'ctl00$PrivateOffice1$cbRememberMe': 'on',
    'ctl00$PrivateOffice1$tbEmailForPassword': '',
    'ctl00_PrivateOffice1_RadToolTip1_ClientState': '',
    'ctl00$DebtorSearch1$inputDebtor': 'поиск',
    'ctl00$cphBody$tbMessageNumber': '',
    'ctl00$cphBody$mdsMessageType$tbSelectedText': '',
    'ctl00$cphBody$mdsMessageType$hfSelectedValue': '',
    'ctl00$cphBody$mdsMessageType$hfSelectedType': '',
    'ctl00$cphBody$ddlCourtDecisionType': '',
    'ctl00$cphBody$mdsPublisher$tbSelectedText': '',
    'ctl00$cphBody$mdsPublisher$hfSelectedValue': '',
    'ctl00$cphBody$mdsPublisher$hfSelectedType': '',
    'ctl00$cphBody$ucRegion$ddlBoundList': '',
    'ctl00$cphBody$mdsDebtor$tbSelectedText': '',
    'ctl00$cphBody$mdsDebtor$hfSelectedValue': '',
    'ctl00$cphBody$mdsDebtor$hfSelectedType': '',
    'ctl00$cphBody$cldrBeginDate$tbSelectedDate': '',
    'ctl00$cphBody$cldrBeginDate$tbSelectedDateValue': '',
    'ctl00$cphBody$cldrEndDate$tbSelectedDate': '',
    'ctl00$cphBody$cldrEndDate$tbSelectedDateValue': '',
    '__ASYNCPOST': 'true',
    '': ''

}