#!/bin/bash
sleep 2
mydir=$HOME
cd $mydir/etp_parsing
source env/bin/activate
cd $mydir/etp_parsing/crawler_bankrot_cdtrf
scrapy crawl bankrot_cd_auction

sleep 5
cd $mydir/etp_parsing
source env/bin/activate
cd $mydir/etp_parsing/crawler_bankrot_cdtrf && \
scrapy crawl bankrot_cd_offer

sleep 2
cd $mydir/etp_parsing
source env/bin/activate
cd $mydir/etp_parsing && \
scrapy crawl bankrot_cd_competition
