# -*- coding: utf-8 -*-
post_data_auction = {
    'ctl00$ctl00$BodyScripts$BodyScripts$scripts': 'ctl00$ctl00$MainExpandableArea$phExpandCollapse$UpdatePanel1|ctl00$ctl00$MainExpandableArea$phExpandCollapse$SearchButton',
    '__EVENTTARGET': '',
    '__EVENTARGUMENT': '',
    '__CVIEWSTATE': '',
    '__VIEWSTATE': '',
    '__SCROLLPOSITIONX': '0',
    '__SCROLLPOSITIONY': '0',
    '__EVENTVALIDATION': '',
    'ctl00$ctl00$LeftContentLogin$ctl00$Login1$UserName': '',
    'ctl00$ctl00$LeftContentLogin$ctl00$Login1$Password': '',
    'ctl00$ctl00$LeftContentSideMenu$mSideMenu$extAccordionMenu_AccordionExtender_ClientState': '0',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_lotNumber_лота': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_purchaseNumber_аукциона': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_lotTitle_Наименованиелота': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_fullTitle_Наименованиеаукциона': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$Party_contactName_AliasFullOrganizerTitle': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_InitialPrice_Начальнаяценаотруб': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$Party_inn_ИННорганизатора': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$BargainType_PriceForm_Формапредставленияпредложенийоцене': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$Party_kpp_КППорганизатора': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_auctionStartDate_Датапроведенияс_dateInput': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$Party_registeredAddress_Адресрегистрацииорганизатора': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_auctionStartDate_Датапроведенияпо_dateInput': '0-0-0 -1:-1:-1',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_BankruptName_Должник': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_purchaseStatusID_Статус': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_BankruptINN_ИННдолжника': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_BankruptRegionID_Региондолжника': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_BankruptRegionID_Региондолжника_desc': '',
    # 'hiddenInputToUpdateATBuffer_CommonToolkitScripts': '1',
    '__ASYNCPOST': 'true',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$SearchButton': 'Искать аукционы',
}

post_data_auction_pagination = {
    '__EVENTTARGET': '',
    '__EVENTARGUMENT': '',
    '__CVIEWSTATE': '',
    '__VIEWSTATE': '',
    '__SCROLLPOSITIONX': '0',
    '__SCROLLPOSITIONY': '2290',
    '__EVENTVALIDATION': '',
    'ctl00$ctl00$LeftContentLogin$ctl00$Login1$UserName': '',
    'ctl00$ctl00$LeftContentLogin$ctl00$Login1$Password': '',
    'ctl00$ctl00$LeftContentSideMenu$mSideMenu$extAccordionMenu_AccordionExtender_ClientState': '0',
    'ctl00$ctl00$MainContent$ContentPlaceHolderMiddle$documents$DownloadTokenValue': '',
    'ctl00$ctl00$MainContent$ContentPlaceHolderMiddle$documents$RequiredFileTypes': '',
    'ctl00$ctl00$MainContent$ContentPlaceHolderMiddle$documents$CheckedIds': '|',
    'ctl00$ctl00$MainContent$ContentPlaceHolderMiddle$documents$hfAttachmentID': '',
    'ctl00$ctl00$MainContent$ContentPlaceHolderMiddle$documents$hfFileTypeID': '',
    'ctl00$ctl00$MainContent$ContentPlaceHolderMiddle$documents$UploadedFileIds': '',
    'ctl00$ctl00$MainContent$ContentPlaceHolderMiddle$documents$tbCustomFileType': '',
    'ctl00$ctl00$MainContent$ContentPlaceHolderMiddle$documents$tbComments': '',

}

post_data_offer = {
    'ctl00$ctl00$BodyScripts$BodyScripts$scripts': 'ctl00$ctl00$MainExpandableArea$phExpandCollapse$UpdatePanel1|ctl00$ctl00$MainExpandableArea$phExpandCollapse$SearchButton',
    '__EVENTTARGET': '',
    '__EVENTARGUMENT': '',
    '__CVIEWSTATE': '',
    '__VIEWSTATE': '',
    '__SCROLLPOSITIONX': '0',
    '__SCROLLPOSITIONY': '0',
    '__EVENTVALIDATION': '',
    'ctl00$ctl00$LeftContentLogin$ctl00$Login1$UserName': '',
    'ctl00$ctl00$LeftContentLogin$ctl00$Login1$Password': '',
    'ctl00$ctl00$LeftContentSideMenu$mSideMenu$extAccordionMenu_AccordionExtender_ClientState': '0',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_lotNumber_лота': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_purchaseNumber_публичногопредложения': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_lotTitle_Наименованиелота': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_fullTitle_Наименованиепубличногопредложения': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$Party_contactName_AliasFullOrganizerTitle': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_InitialPrice_Начальнаяценаотруб': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$Party_inn_ИННорганизатора': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_ParticipationFormID_Форматоргапосоставуучастников': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$BargainType_PriceForm_Формапредставленияпредложенийоцене': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$Party_kpp_КППорганизатора': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_bidSubmissionStartDate_Датаначалапредставлениязаявокнаучастиес_dateInput': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$Party_registeredAddress_Адресрегистрацииорганизатора': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_bidSubmissionStartDate_Датаначалапредставлениязаявокнаучастиепо_dateInput': '0-0-0 -1:-1:-1',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_BankruptName_Должник': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_purchaseStatusID_Статус': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_BankruptINN_ИННдолжника': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_BankruptRegionID_Региондолжника': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_BankruptRegionID_Региондолжника_desc': '',
    # 'hiddenInputToUpdateATBuffer_CommonToolkitScripts': '1',
    '__ASYNCPOST': 'true',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$SearchButton': 'Искать публичные предложени',
}

post_data_offer_period = {
    '__EVENTTARGET': '',
    '__EVENTARGUMENT': '',
    '__CVIEWSTATE': '',
    '__VIEWSTATE': '',
    '__SCROLLPOSITIONX': '0',
    '__SCROLLPOSITIONY': '0',
    '__EVENTVALIDATION': '',
    'ctl00$ctl00$LeftContentLogin$ctl00$Login1$UserName': '',
    'ctl00$ctl00$LeftContentLogin$ctl00$Login1$Password': '',
    'ctl00$ctl00$LeftContentSideMenu$mSideMenu$extAccordionMenu_AccordionExtender_ClientState': '0',
    'ctl00$ctl00$MainContent$ContentPlaceHolderMiddle$AttachmentsControl$DownloadTokenValue': '',
    'ctl00$ctl00$MainContent$ContentPlaceHolderMiddle$AttachmentsControl$RequiredFileTypes': '',
    'ctl00$ctl00$MainContent$ContentPlaceHolderMiddle$AttachmentsControl$CheckedIds': '|',
    'ctl00$ctl00$MainContent$ContentPlaceHolderMiddle$AttachmentsControl$hfAttachmentID': '',
    'ctl00$ctl00$MainContent$ContentPlaceHolderMiddle$AttachmentsControl$hfFileTypeID': '',
    'ctl00$ctl00$MainContent$ContentPlaceHolderMiddle$AttachmentsControl$UploadedFileIds': '',
    'ctl00$ctl00$MainContent$ContentPlaceHolderMiddle$AttachmentsControl$tbCustomFileType': '',
    'ctl00$ctl00$MainContent$ContentPlaceHolderMiddle$AttachmentsControl$tbComments': '',

}

post_data_competition = {
    'ctl00$ctl00$BodyScripts$BodyScripts$scripts': 'ctl00$ctl00$MainExpandableArea$phExpandCollapse$UpdatePanel1|ctl00$ctl00$MainExpandableArea$phExpandCollapse$SearchButton',
    '__EVENTTARGET': '',
    '__EVENTARGUMENT': '',
    '__CVIEWSTATE': '',
    '__VIEWSTATE': '',
    '__SCROLLPOSITIONX': '0',
    '__SCROLLPOSITIONY': '0',
    '__EVENTVALIDATION': '',
    'ctl00$ctl00$LeftContentLogin$ctl00$Login1$UserName': '',
    'ctl00$ctl00$LeftContentLogin$ctl00$Login1$Password': '',
    'ctl00$ctl00$LeftContentSideMenu$mSideMenu$extAccordionMenu_AccordionExtender_ClientState': '0',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_lotNumber_лота': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_purchaseNumber_конкурса': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_lotTitle_Наименованиелота': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_fullTitle_Наименованиеконкурса': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$Party_contactName_AliasFullOrganizerTitle': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_InitialPrice_Начальнаяценаотруб': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$Party_inn_ИННорганизатора': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$BargainType_PriceForm_Формапредставленияпредложенийоцене': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$Party_kpp_КППорганизатора': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_auctionStartDate_Датапроведенияс_dateInput': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$Party_registeredAddress_Адресрегистрацииорганизатора': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_auctionStartDate_Датапроведенияпо_dateInput:': '0-0-0 -1:-1:-1',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_BankruptName_Должник': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_purchaseStatusID_Статус': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_BankruptINN_ИННдолжника': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_BankruptRegionID_Региондолжника': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$PurchasesSearchCriteria$vPurchaseLot_BankruptRegionID_Региондолжника_desc': '',
    # 'hiddenInputToUpdateATBuffer_CommonToolkitScripts': '1',
    '__ASYNCPOST': 'true',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$SearchButton': 'Искать конкурсы',
}