post_data_utender_offer = {
    'ctl00$ctl00$BodyScripts$BodyScripts$scripts': 'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$ctl00|ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$btnSearch',
    '__EVENTTARGET': '',
    '__EVENTARGUMENT': '',
    '__CVIEWSTATE': '',
    '__VIEWSTATE': '',
    '__SCROLLPOSITIONX': '0',
    '__SCROLLPOSITIONY': '0',
    '__EVENTVALIDATION': '',
    'ctl00$ctl00$LeftContentLogin$ctl00$Login1$UserName': '',
    'ctl00$ctl00$LeftContentLogin$ctl00$Login1$Password': '',
    'ctl00$ctl00$LeftContentSideMenu$mSideMenu$extAccordionMenu_AccordionExtender_ClientState': '0',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_lotNumber_лота': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_purchaseNumber_публичногопредложения': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_lotTitle_Наименованиелота': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_fullTitle_Наименованиепубличногопредложения': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_procurementClassifierID_Категориялота': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_procurementClassifierID_Категориялота_desc': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_initialContractPriceValue_Начальнаяценаотруб': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$Party_contactName_AliasFullOrganizerTitle': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$Purchase_bidSubmissionStartDate_Датаначалапредставлениязаявокнаучастиес_dateInput': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$Party_inn_ИННорганизатора': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$Purchase_bidSubmissionStartDate_Датаначалапредставлениязаявокнаучастиепо_dateInput': '0-0-0 -1:-1:-1',
    # 'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$Purchase_bidSubmissionStartDate_Датаначалапредставлениязаявокнаучастиепо_dateInput': '2018-10-3 0:0:-1',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$Party_kpp_КППорганизатора': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_purchaseStatusID_Статус': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$Party_registeredAddress_Адресрегистрацииорганизатора': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_BankruptName_Должник': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_BankruptINN_ИННдолжника': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_BankruptRegionID_Региондолжника': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_BankruptRegionID_Региондолжника_desc': '',
    'hiddenInputToUpdateATBuffer_CommonToolkitScripts': '1',
    '__ASYNCPOST': 'true',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$btnSearch': 'Искать публичные предложения',

}

post_data_utender_auction = {
    'ctl00$ctl00$BodyScripts$BodyScripts$scripts': 'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$ctl00|ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$btnSearch',
    '__EVENTTARGET': '',
    '__EVENTARGUMENT': '',
    '__CVIEWSTATE': '',
    '__VIEWSTATE': '',
    '__SCROLLPOSITIONX': '0',
    '__SCROLLPOSITIONY': '0',
    '__EVENTVALIDATION': '',
    'ctl00$ctl00$LeftContentLogin$ctl00$Login1$UserName': '',
    'ctl00$ctl00$LeftContentLogin$ctl00$Login1$Password': '',
    'ctl00$ctl00$LeftContentSideMenu$mSideMenu$extAccordionMenu_AccordionExtender_ClientState': '0',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_lotNumber_лота': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_purchaseNumber_аукциона': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_lotTitle_Наименованиелота': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_fullTitle_Наименованиеаукциона': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_procurementClassifierID_Категориялота': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_procurementClassifierID_Категориялота_desc': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_initialContractPriceValue_Начальнаяценаотруб': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$Party_contactName_AliasFullOrganizerTitle': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$BargainType_PriceForm_Формапредставленияпредложенийоцене': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$Party_inn_ИННорганизатора': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_auctionStartDate_Датапроведенияс_dateInput': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$Party_kpp_КППорганизатора': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_auctionStartDate_Датапроведенияпо_dateInput': '0-0-0 -1:-1:-1',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$Party_registeredAddress_Адресрегистрацииорганизатора': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_purchaseStatusID_Статус': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_BankruptName_Должник': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_BankruptINN_ИННдолжника': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_BankruptRegionID_Региондолжника': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_BankruptRegionID_Региондолжника_desc': '',
    'hiddenInputToUpdateATBuffer_CommonToolkitScripts': '1',
    '__ASYNCPOST': 'true',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$btnSearch': 'Искать аукционы',


}

post_data_utender_competition = {
    'ctl00$ctl00$BodyScripts$BodyScripts$scripts': 'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$ctl00|ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$btnSearch',
    '__EVENTTARGET': '',
    '__EVENTARGUMENT': '',
    '__CVIEWSTATE': '',
    '__VIEWSTATE': '',
    '__SCROLLPOSITIONX': '0',
    '__SCROLLPOSITIONY': '0',
    '__EVENTVALIDATION': '',
    'ctl00$ctl00$LeftContentLogin$ctl00$Login1$UserName': '',
    'ctl00$ctl00$LeftContentLogin$ctl00$Login1$Password': '',
    'ctl00$ctl00$LeftContentSideMenu$mSideMenu$extAccordionMenu_AccordionExtender_ClientState': '0',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_lotNumber_лота': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_purchaseNumber_конкурса': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_lotTitle_Наименованиелота': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_fullTitle_Наименованиеконкурса': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_procurementClassifierID_Категориялота': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_procurementClassifierID_Категориялота_desc': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_initialContractPriceValue_Начальнаяценаотруб': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$Party_contactName_AliasFullOrganizerTitle': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$BargainType_PriceForm_Формапредставленияпредложенийоцене': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$Party_inn_ИННорганизатора': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$Purchase_AuctionStartDate_Датапроведенияс_dateInput': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$Party_kpp_КППорганизатора': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$Purchase_AuctionStartDate_Датапроведенияпо_dateInput': '0-0-0 -1:-1:-1',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$Party_registeredAddress_Адресрегистрацииорганизатора': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_purchaseStatusID_Статус': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_BankruptName_Должник': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_BankruptINN_ИННдолжника': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_BankruptRegionID_Региондолжника': '',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$SearchCriteria1$vPurchaseLot_BankruptRegionID_Региондолжника_desc': '',
    'hiddenInputToUpdateATBuffer_CommonToolkitScripts': '1',
    '__ASYNCPOST': 'true',
    'ctl00$ctl00$MainExpandableArea$phExpandCollapse$ctl00$btnSearch': 'Искать конкурсы',

}

post_data_lot_pagination_utender = {
    '__EVENTTARGET': '',
    '__EVENTARGUMENT': '',
    '__CVIEWSTATE': '',
    '__VIEWSTATE': '',
    '__SCROLLPOSITIONX': '0',
    '__SCROLLPOSITIONY': '2290',
    '__EVENTVALIDATION': '',
    'ctl00$ctl00$LeftContentLogin$ctl00$Login1$UserName': '',
    'ctl00$ctl00$LeftContentLogin$ctl00$Login1$Password': '',
    'ctl00$ctl00$LeftContentSideMenu$mSideMenu$extAccordionMenu_AccordionExtender_ClientState': '0',
    'ctl00$ctl00$MainContent$ContentPlaceHolderMiddle$ctl00$attCtrl$upTrigger': ''
}


post_data_offer_period = {
    '__EVENTTARGET': '',
    '__EVENTARGUMENT': '',
    '__CVIEWSTATE': '',
    '__VIEWSTATE': '',
    '__SCROLLPOSITIONX': '0',
    '__SCROLLPOSITIONY': '0',
    '__EVENTVALIDATION': '',
    'ctl00$ctl00$LeftContentLogin$ctl00$Login1$UserName': '',
    'ctl00$ctl00$LeftContentLogin$ctl00$Login1$Password': '',
    'ctl00$ctl00$LeftContentSideMenu$mSideMenu$extAccordionMenu_AccordionExtender_ClientState': '0',
    'ctl00$ctl00$MainContent$ContentPlaceHolderMiddle$AttachmentsControl$DownloadTokenValue': '',
    'ctl00$ctl00$MainContent$ContentPlaceHolderMiddle$AttachmentsControl$RequiredFileTypes': '',
    'ctl00$ctl00$MainContent$ContentPlaceHolderMiddle$AttachmentsControl$CheckedIds': '|',
    'ctl00$ctl00$MainContent$ContentPlaceHolderMiddle$AttachmentsControl$hfAttachmentID': '',
    'ctl00$ctl00$MainContent$ContentPlaceHolderMiddle$AttachmentsControl$hfFileTypeID': '',
    'ctl00$ctl00$MainContent$ContentPlaceHolderMiddle$AttachmentsControl$UploadedFileIds': '',
    'ctl00$ctl00$MainContent$ContentPlaceHolderMiddle$AttachmentsControl$tbCustomFileType': '',
    'ctl00$ctl00$MainContent$ContentPlaceHolderMiddle$AttachmentsControl$tbComments': '',

}